export namespace DocsConstants {
	export const acceptableDocFields: string[] = [
		"need_recipient_signature",
		"link_contr_system",
		"counterparties_id",
		"counterparty_id",
		"document_kind",
		"kontragent_id",
		"is_cancelled",
		"is_internal",
		"is_template",
		"reg_number",
		"kontragent",
		"is_roaming",
		"lock_mode",
		"reg_date",
		"boxes_id",
		"comment",
		"is_test",
		"docs_id",
		"doc_id",
		"org_id",
		"name",
		"sum",
		"vgo",

		"system_id" // TODO: временно оставлено до доработок смежных систем
	]

	/** Сопоставление типа файла и обязательных полей в документе */
	export const nonStructuredKeys: Record<string, string[]> = {
		StorageInventoryAcceptanceCertificate: [],
		ReturnInventoryAcceptanceCertificate: [],
		UniversalCorrectionDocumentRevision: [],
		PerformedWorkAcceptanceCertificate: [],
		UniversalTransferDocumentRevision: [],
		AcceptanceCertificate: ["total_vat"],
		LogisticsContainerCertificate: [],
		UniversalCorrectionDocument: [],
		LogisticsWaybillForwarding: [],
		UniversalTransferDocument: [],
		InvoiceCorrectionRevision: [],
		LogisticsCharterAgreement: [],
		LogisticsWaybillReception: [],
		XmlAcceptanceCertificate: [],
		LogisticsWaybillDelivery: [],
		TrustConnectionRequest: [],
		SupplementaryAgreement: [],
		Torg13: ["currency_code"],
		LogisticsOrderRequest: [],
		CertificateRegistry: [],
		PriceListAgreement: [],
		LogisticsWorkOrder: [],
		ReconciliationAct: [],
		InvoiceCorrection: [],
		LogisticsWaybill: [],
		ProformaInvoice: [],
		PowerOfAttorney: [],
		InvoiceRevision: [],
		ServiceDetails: [],
		Nonformalized: [],
		LogisticsEpl: [],
		PriceList: [],
		XmlTorg12: [],
		Contract: [],
		Invoice: [],
		Waybill: [],
		common: [],
		Torg12: [],
		Letter: [],
		Torg2: []
	}
}
