export const CONFIG__CACHE_BASE_TTL: string = "CACHE__BASE_TTL"
export const CONFIG__RUN_MODE: string = "RUN_MODE"
export const CONFIG__NODE_ENV: string = "NODE_ENV"
export const CONFIG__APP_ENV: string = "APP_ENV"

export const CONFIG__STORING_MONTHS_FILES: string = "STORING__MONTHS_FILES"
export const CONFIG__STORING_MONTHS_DOCUMENT_DRAFTS: string =
	"STORING__MONTHS_DOCUMENT_DRAFTS"

export const CONFIG__SA_USERNAME: string = "SA__USER"
export const CONFIG__SA_PASSWORD: string = "SA__PASSWORD"

export const CONFIG__MDM_COUNTERPARTIES_PATH: string = "MDM_COUNTERPARTIES_PATH"
export const CONFIG__MDM_ORGANIZATION_PATH: string = "MDM_ORGANIZATION_PATH"

export const CONFIG__HEALTH_REST_BASE_URL: string = "HEALTH__REST_BASE_URL"
export const CONFIG__HEALTH_GRPC_BASE_URL: string = "HEALTH__GRPC_BASE_URL"

export const CONFIG__S3_ACCESS_DOMAIN_NAME: string = "S3_ACCESS_DOMAIN_NAME"
export const CONFIG__S3_BUCKET_LOGS: string = "S3_BUCKET_LOGS"
export const CONFIG__S3_ENDPOINT: string = "S3_ENDPOINT"
export const CONFIG__S3_USE_SSL: string = "S3_USE_SSL"
export const CONFIG__S3_BUCKET: string = "S3_BUCKET"
export const CONFIG__S3_PORT: string = "S3_PORT"

export const CONFIG__REDIS_PORT: string = "REDIS__PORT"

export const CONFIG__SENTRY_VERSION: string = "SENTRY_VERSION"
export const CONFIG__SENTRY_DSN: string = "SENTRY__DSN"

export const CONFIG__GRPC_CA_CERT_FILE: string = "CA_CERT_FILE"
export const CONFIG__GRPC_PROTO_PATH: string = "GRPC__PROTO_PATH"
export const CONFIG__GRPC_IS_SECURED: string = "GRPC__IS_SECURED"
export const CONFIG__GRPC_CERT_FILE: string = "SERVER_KEY_FILE"
export const CONFIG__GRPC_KEY_FILE: string = "SERVER_CERT_FILE"
export const CONFIG__GRPC_PACKAGE: string = "GRPC__PACKAGE"
export const CONFIG__GRPC_LOADER: string = "GRPC__LOADER"
export const CONFIG__GRPC_HOST: string = "GRPC__HOST"
export const CONFIG__GRPC_PORT: string = "GRPC__PORT"

export const BULL_DOWNLOADER_QUEUE: string = "BULL_DOWNLOADER_QUEUE"
export const BULL_PROCESSOR_QUEUE: string = "BULL_PROCESSOR_QUEUE"

export const BULL_PRINTING_FORMS_EVENT: string = "BULL_PRINTING_FORMS_EVENT"
export const BULL_ONE_FILE_DOWNLOADER: string = "BULL_ONE_FILE_DOWNLOADER"
export const BULL_DOWNLOAD_PRINT_FORM_HANDLER_EVENT: string =
	"BULL_DOWNLOAD_PRINT_FORM_HANDLER_EVENT"
export const BULL_DOWNLOAD_ARCHIVE_HANDLER_EVENT: string =
	"BULL_DOWNLOAD_ARCHIVE_HANDLER_EVENT"

/** Diadoc client constants */
export const DIADOC_GET_ROAMING_OPERATORS_PATH: string =
	"DIADOC_GET_ROAMING_OPERATORS_PATH"
export const DIADOC_DELETE_DOCUMENT_PATH: string = "DIADOC_DELETE_DOCUMENT_PATH"
export const DIADOC_PRINTING_FORMS_PATH: string = "DIADOC_PRINTING_FORMS_PATH"
export const DIADOC_SEND_DOCUMENT_PATH: string = "DIADOC_SEND_DOCUMENT_PATH"
export const RETRY__DELAY_MILLISECONDS = "RETRY__DELAY_MILLISECONDS"
export const DIADOC_CHECK_STATUS_PATH: string = "DIADOC_CHECK_STATUS_PATH"
export const DIADOC_ARCHIVE_DOWNLOAD: string = "DIADOC_ARCHIVE_DOWNLOAD"
export const DIADOC_ARCHIVE_PREPARE: string = "DIADOC_ARCHIVE_PREPARE"
export const DIADOC_AUTH_PASSWORD: string = "DIADOC_AUTH_PASSWORD"
export const DIADOC_GET_ORGANIZATION_FEATURES =
	"DIADOC_GET_ORGANIZATION_FEATURES"
export const GET_ROAMING_BOX_ID: string = "GET_ROAMING_BOX_ID"
export const DIADOC_GET_ORGANIZATIONS_INN_LIST_PATH: string =
	"DIADOC_GET_ORGANIZATIONS_INN_LIST_PATH"
export const DIADOC_GET_ORGANIZATIONS_INN_KPP_PATH: string =
	"DIADOC_GET_ORGANIZATIONS_INN_KPP_PATH"
export const DIADOC_AUTH_LOGIN: string = "DIADOC_AUTH_LOGIN"
export const DIADOC_AUTH_PATH: string = "DIADOC_AUTH_PATH"
export const DIADOC_TOKEN_TTL: string = "DIADOC_TOKEN_TTL"
export const DIADOC_SEND_TEMPLATE_DOCUMENT_PATH: string =
	"DIADOC_SEND_TEMPLATE_DOCUMENT_PATH"
export const DIADOC_CHECK_CAN_DELETE_PATH: string =
	"DIADOC_CHECK_CAN_DELETE_PATH"
export const DIADOC_DEV_KEY: string = "DIADOC_DEV_KEY"
export const DIADOC_API_URL: string = "DIADOC_API_URL"
export const DIADOC_URL: string = "DIADOC_URL"
