export const IOC__INTERCEPTOR__GRPC_CACHE: string =
	"IOC__INTERCEPTOR__GRPC_CACHE"
export const IOC__INTERCEPTOR__SENTRY: string = "IOC__INTERCEPTOR__SENTRY"

export const IOC__SERVICE__DOCS_RECIPIENT_DB: string =
	"IOC__SERVICE__DOCS_RECIPIENT_DB"
export const IOC__SERVICE__FILES_DOWNLOAD: string =
	"IOC__SERVICE__FILES_DOWNLOAD"
export const IOC__SERVICE__FILES_CLEANER: string = "IOC__SERVICE__FILES_CLEANER"
export const IOC__SERVICE__ORGANIZATION_DB: string =
	"IOC__SERVICE__ORGANIZATION_DB"
export const IOC__SERVICE__COUNTERPARTY_DB: string =
	"IOC__SERVICE__COUNTERPARTY_DB"
export const IOC__SERVICE__ROAMING_OPERATORS_DB: string =
	"IOC__SERVICE__ROAMING_OPERATORS_DB"
export const IOC__SERVICE__DOCS_LINKS_DB: string = "IOC__SERVICE__DOCS_LINKS_DB"
export const IOC__SERVICE__DELETE_DOCS: string = "IOC__SERVICE__DELETE_DOCS"
export const IOC__SERVICE__SYSTEMS_DB: string = "IOC__SERVICE__SYSTEMS_DB"
export const IOC__SERVICE__PACKETS_DB: string = "IOC__SERVICE__PACKETS_DB"
export const IOC__SERVICE__STATUS_DB: string = "IOC__SERVICE__STATUS_DB"
export const IOC__SERVICE__OPERATORS: string = "IOC__SERVICE__OPERATORS"
export const IOC__SERVICE__DIADOC: string = "IOC__SERVICE__DIADOC"
export const IOC__SERVICE__FILES: string = "IOC__SERVICE__FILES"
export const IOC__SERVICE__LOGS: string = "IOC__SERVICE__LOGS"
export const IOC__SERVICE__DOCS: string = "IOC__SERVICE__DOCS"
export const IOC__SERVICE__MDM: string = "IOC__SERVICE__MDM"
export const IOC__SERVICE__CLIENT_PROVIDER_REDIS_BULL: string =
	"IOC__SERVICE__CLIENT_PROVIDER_REDIS_BULL"
export const IOC__SERVICE__CLIENT_PROVIDER_DIADOC: string =
	"IOC__SERVICE__CLIENT_PROVIDER_DIADOC"
export const IOC__SERVICE__CLIENT_PROVIDER_REDIS: string =
	"IOC__SERVICE__CLIENT_PROVIDER_REDIS"
export const IOC__SERVICE__OBSERVABILITY_SENTRY: string =
	"IOC__SERVICE__OBSERVABILITY_SENTRY"
export const IOC__SERVICE__CLIENT_PROVIDER_MDM: string =
	"IOC__SERVICE__CLIENT_PROVIDER_MDM"
export const IOC__SERVICE__CLIENT_PROVIDER_S3: string =
	"IOC__SERVICE__CLIENT_PROVIDER_S3"

export const IOC__SERVICE__FILES_DB: string = "IOC__SERVICE__FILES_DB"
export const IOC__SERVICE__DOCS_DB: string = "IOC__SERVICE__DOCS_DB"

export const IOC__CLIENT_PROVIDER__KAFKA: string = "IOC__CLIENT_PROVIDER__KAFKA"
export const IOC__CLIENT_PROVIDER__SELF: string = "IOC__CLIENT_PROVIDER__SELF"
export const IOC__CLIENT_PROVIDER__KAFKA_WRAPPER: string =
	"IOC__CLIENT_PROVIDER__KAFKA_WRAPPER"

export const IOC__CRON_STORING_SERVICE: string = "IOC__CRON_STORING_SERVICE"
export const IOC__CRON_SIGNING_SERVICE: string = "IOC__CRON_SIGNING_SERVICE"

export const IOC__CRON_LOGS_SERVICE: string = "IOC__CRON_LOGS_SERVICE"

export const IOC__MDM_REFRESHING_SERVICE: string = "IOC__MDM_REFRESHING_SERVICE"
export const IOC__DIADOC_REFRESHING_SERVICE: string =
	"IOC__DIADOC_REFRESHING_SERVICE"
export const IOC__BASE_REFRESHING_SERVICE: string =
	"IOC__BASE_REFRESHING_SERVICE"
export const IOC__BACKSTAGE_SERVICE: string = "IOC__BACKSTAGE_SERVICE"
export const IOC__WORKER_SERVICE: string = "IOC__WORKER_SERVICE"
export const IOC__KAFKA_SERVICE: string = "IOC__KAFKA_SERVICE"
export const IOC__ADMIN_SERVICE: string = "IOC__ADMIN_SERVICE"
export const IOC__AUTH_SERVICE: string = "IOC__AUTH_SERVICE"
export const IOC__STATUS_REFRESHING_SERVICE: string =
	"IOC__STATUS_REFRESHING_SERVICE"
export const IOC__FILES_PROCESSING_SERVICE: string =
	"IOC__FILES_PROCESSING_SERVICE"

export const IOC__SERVICE__ERROR_LOGS_DB: string = "IOC__SERVICE__ERROR_LOGS_DB"
export const IOC__SERVICE__ERROR_LOGS: string = "IOC__SERVICE__ERROR_LOGS"

export const IOC__REDIS_INDICATOR: string = "IOC__REDIS_INDICATOR"
export const IOC__COUNTERPARTIES_INDICATOR: string =
	"IOC__COUNTERPARTIES_INDICATOR"
export const IOC__ORGANIZATIONS_INDICATOR: string =
	"IOC__ORGANIZATIONS_INDICATOR"

export const IOC__GRPC_SELF_CLIENT: string = "IOC__GRPC_SELF_CLIENT"
