{{- if .Values.worker.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.fullname" . }}-worker
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "project.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.podPorts.name }}
              containerPort: {{ .Values.podPorts.containerPort }}
              protocol: {{ .Values.podPorts.protocol }}
          {{/*    TODO: Liveness / Readiness      */}}
          livenessProbe:
            exec:
              command:
                - cat
                - /opt/app/dist/main.js
            initialDelaySeconds: 3
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - cat
                - /opt/app/dist/main.js
            initialDelaySeconds: 3
            periodSeconds: 60
{{/*          {{- if .Values.podLivenessProbe }}*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml .Values.podLivenessProbe | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- if .Values.podReadinessProbe }}*/}}
{{/*          readinessProbe:*/}}
{{/*          {{- toYaml .Values.podReadinessProbe | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: RUN_MODE
              value: "MODE_WORKER"
          envFrom:
            {{- .Values.commonEnvFrom | toYaml | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
