apiVersion: v1
kind: Service
metadata:
  name: service-{{ include "project.fullname" . }}-rest
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.podPorts.containerPort }}
      protocol: {{ .Values.podPorts.protocol }}
      name: {{ .Values.podPorts.name }}
  selector:
    {{- include "project.selectorLabels" . | nindent 4 }}

---
{{- if .Values.worker.app}}
apiVersion: v1
kind: Service
metadata:
  name: service-{{ include "project.fullname" . }}-worker
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.podPorts.containerPort }}
      protocol: {{ .Values.podPorts.protocol }}
      name: {{ .Values.podPorts.name }}
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}
{{- end }}

